apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: e2e-tests-go-sznpfgki-workflow 
  janus-idp.io/tekton: e2e-tests-go-sznpfgki-workflow
  backstage.io/kubernetes-id: e2e-tests-go-sznpfgki-workflow
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e2e-tests-go-sznpfgki-workflow
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml